### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 2: invalid continuation byte

### ISSUE THREAD

**Issue by gegentan** [fujiisoup/lstpy#13]
Code:

```
import lstpy

fl = lstpy.load("flmain.lst")
print(fl)
```

Output:

```
Traceback (most recent call last):
  File "c:\Users\user\Desktop\hd\main.py", line 3, in <module>
    fl = lstpy.load("flmain.lst")
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\lstpy\load.py", line 45, in load
    file, header, version, is_ascii = _read_header(file)
                                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\lstpy\load.py", line 180, in _read_header
    line = file.readline().decode('utf-8').strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 2: invalid continuation byte
```

**Comment by fujiisoup** [comment]
What does your header look like? 
It looks like your header contains some non-unicode character. Probably the path contains a user-name, which uses non-ascii character?

If you could share the smallest file that causes this error, I think I can fix it.
